### ISSUE TITLE
Constructor Sandbox Parameter is misleading

### ISSUE THREAD

**Issue by cdaguerre** [checkout/checkout-sdk-php#42]
The second argument of the `CheckoutApi` [constructor](https://github.com/checkout/checkout-sdk-php/blob/master/src/CheckoutApi.php#L154) is pretty misleading as PHP developers would generally expect `-1` to be equivalent to `false`, or at least definitely not the same as `true` ;).

```php
$api = new CheckoutApi('<secret_key>'); // sandbox mode
$api = new CheckoutApi('<secret_key>', true); // sandbox mode
$api = new CheckoutApi('<secret_key>', -1); // sandbox mode
$api = new CheckoutApi('<secret_key>', false); // production mode
```

**Comment by aquila-freitas-cko** [comment]
Hi @cdaguerre , 
I understand the confusion, I would say `$api = new CheckoutApi('<secret_key>', -1); // config mode`. When we designed the entry point of the SDK we wanted to set some definitions on a separate file (`src/config.ini`) and later we found necessary to create the a "shortcut" to sandbox mode from the constructor. The solution was to give a value that wasn't either boolean true or false.

The [comments](https://github.com/checkout/checkout-sdk-php/blob/master/src/CheckoutApi.php#L150) of the constructor say that `sandbox` parameter is boolean, in order to prevent developers of following the default value of `-1`. If you keep following the code you will see that there is another [comment](https://github.com/checkout/checkout-sdk-php/blob/master/src/CheckoutApi.php#L295) where the `-1` is actually being used.

Personally, I also find this unnecessarily "not simple". This was an attempt to please everyone that was very beautiful on design but not beneficial in practice. There is already plans to change this on next major release, we will drop the `$sandbox` parameter of the constructor and select the environment from the prefix of the secret key and we will eventually remove `config.ini` and move it to `composer.json`.

If you have any suggestions, feel free to leave them here or make a pull request. I will take them to discussion with the rest of the team.
