### ISSUE TITLE
Getting a "server_api_not_allowed" Error

### ISSUE THREAD

**Issue by HElwy** [checkout/checkout-sdk-php#50]
Just starting to use this package in a Laravel project, used composer to install it, and added a payment function for it

```
$secretKey = 'sk_test_111';
$checkout = new CheckoutApi($secretKey);
$method = new CardSource('5436031030606378', 12, 2024);
$method->cvv = '257';
$payment = new CkPayment($method, 'GBP');
$payment->capture = false;
$payment->amount = 1000;
try {
    $checkout->payments()->request($payment);
} catch (CheckoutHttpException $e) {
    dd($e);
    return false;
}
```

I keep getting this error
```
Checkout\Library\Exceptions\CheckoutHttpException {#312 ▼
  #body: "{"request_id":"111","error_type":"processing_error","error_codes":["server_api_not_allowed"]}"
  #errors: array:1 [▶]
  #message: "The endpoint did not accept the request. (Code: 500)"
  #code: 500
  #file: "/home/vagrant/xyz/vendor/checkout/checkout-sdk-php/src/Library/HttpHandler.php"
  #line: 327
  trace: {▶}
}
```

**Comment by aquila-freitas-cko** [comment]
Interesting, first time I see this error.
Can you update `$checkout->payments()->request($payment);` to `$checkout->payments()->request($payment, FALSE);` and share it. Note this will expose you secret and public key.

**Comment by aquila-freitas-cko** [comment]
Hi @HElwy ,
In order to make payments using card details you need to have Full Card API enabled in your account, you can learn more about compliance [here](https://docs.checkout.com/docs/pci-compliance). I recommend you to use Checkout.com Frames Integration to safely tokenise your card and create TokenSource in your payment. This will allow you to use cards in a secure manner. See how to integrate Frames [here](https://docs.checkout.com/docs/frames).

Best regards,
@aquila-freitas-cko
